/*
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.grupox.ide.contentassist.antlr.internal.InternalTeamworkParser;
import org.xtext.grupox.services.TeamworkGrammarAccess;

public class TeamworkParser extends AbstractContentAssistParser {

	@Inject
	private TeamworkGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalTeamworkParser createParser() {
		InternalTeamworkParser result = new InternalTeamworkParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProjectAccess().getAlternatives(), "rule__Project__Alternatives");
					put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
					put(grammarAccess.getTeamworkAccess().getElementsAssignment(), "rule__Teamwork__ElementsAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalTeamworkParser typedParser = (InternalTeamworkParser) parser;
			typedParser.entryRuleTeamwork();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TeamworkGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TeamworkGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
