/*
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.grupox.teamwork.ui.internal.TeamworkActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TeamworkExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TeamworkActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TeamworkActivator.getInstance().getInjector(TeamworkActivator.ORG_XTEXT_GRUPOX_TEAMWORK);
	}
	
}
