/**
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.validation;

import org.xtext.grupox.validation.AbstractTeamworkValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TeamworkValidator extends AbstractTeamworkValidator {
}
