/**
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.grupox.ui.AbstractTeamworkUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TeamworkUiModule extends AbstractTeamworkUiModule {
  public TeamworkUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
