/**
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox;

import org.xtext.grupox.TeamworkStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TeamworkStandaloneSetup extends TeamworkStandaloneSetupGenerated {
  public static void doSetup() {
    TeamworkStandaloneSetup _teamworkStandaloneSetup = new TeamworkStandaloneSetup();
    _teamworkStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
