/*
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTeamworkScopeProvider extends DelegatingScopeProvider {
}
