/*
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.grupox.services.TeamworkGrammarAccess;
import org.xtext.grupox.teamwork.Teamwork;
import org.xtext.grupox.teamwork.TeamworkPackage;

@SuppressWarnings("all")
public class TeamworkSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private TeamworkGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == TeamworkPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TeamworkPackage.TEAMWORK:
				sequence_Teamwork(context, (Teamwork) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Teamwork returns Teamwork
	 *
	 * Constraint:
	 *     elements+=Project+
	 */
	protected void sequence_Teamwork(ISerializationContext context, Teamwork semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
