/*
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.grupox.teamwork.ui.internal.TeamworkActivator;

public class TeamworkUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TeamworkActivator.getInstance().getInjector("org.xtext.grupox.Teamwork");
	}

}
