/**
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.teamwork.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.grupox.teamwork.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TeamworkFactoryImpl extends EFactoryImpl implements TeamworkFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TeamworkFactory init()
  {
    try
    {
      TeamworkFactory theTeamworkFactory = (TeamworkFactory)EPackage.Registry.INSTANCE.getEFactory(TeamworkPackage.eNS_URI);
      if (theTeamworkFactory != null)
      {
        return theTeamworkFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TeamworkFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TeamworkFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TeamworkPackage.TEAMWORK: return createTeamwork();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Teamwork createTeamwork()
  {
    TeamworkImpl teamwork = new TeamworkImpl();
    return teamwork;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TeamworkPackage getTeamworkPackage()
  {
    return (TeamworkPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TeamworkPackage getPackage()
  {
    return TeamworkPackage.eINSTANCE;
  }

} //TeamworkFactoryImpl
