/**
 * generated by Xtext 2.10.0
 */
package org.xtext.grupox.teamwork.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.grupox.teamwork.Teamwork;
import org.xtext.grupox.teamwork.TeamworkFactory;
import org.xtext.grupox.teamwork.TeamworkPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TeamworkPackageImpl extends EPackageImpl implements TeamworkPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass teamworkEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.grupox.teamwork.TeamworkPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private TeamworkPackageImpl()
  {
    super(eNS_URI, TeamworkFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link TeamworkPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static TeamworkPackage init()
  {
    if (isInited) return (TeamworkPackage)EPackage.Registry.INSTANCE.getEPackage(TeamworkPackage.eNS_URI);

    // Obtain or create and register package
    TeamworkPackageImpl theTeamworkPackage = (TeamworkPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof TeamworkPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new TeamworkPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theTeamworkPackage.createPackageContents();

    // Initialize created meta-data
    theTeamworkPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theTeamworkPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(TeamworkPackage.eNS_URI, theTeamworkPackage);
    return theTeamworkPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTeamwork()
  {
    return teamworkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTeamwork_Elements()
  {
    return (EAttribute)teamworkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TeamworkFactory getTeamworkFactory()
  {
    return (TeamworkFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    teamworkEClass = createEClass(TEAMWORK);
    createEAttribute(teamworkEClass, TEAMWORK__ELEMENTS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(teamworkEClass, Teamwork.class, "Teamwork", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTeamwork_Elements(), ecorePackage.getEString(), "elements", null, 0, -1, Teamwork.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //TeamworkPackageImpl
